### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by andrewleader** [FrecherxDachs/UwpNotificationNetCoreTest#1]
Hey @FrecherxDachs, I'm from the Windows notifications team at Microsoft. Big thanks for figuring out how to use the COM server in .NET Core 3.0!

Your repo is missing a license... could you add a license if we can use your code in our DesktopNotificationManagerCompat library (which also gets included in the Windows Community Toolkit) so that everyone can benefit from this?

**Comment by michael-hawker** [comment]
MIT would be the most agreeable with the Toolkit, thanks! 🙂

**Comment by MichaeIDietrich** [comment]
Nice to hear that I could help a bit. 
MIT license added.
